experiment_name: variance_oneshot
run_name: equalize_weights_full_dataset_large
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/workshop/instance_seg/2024-07-17_14-34-16/checkpoints/last.ckpt"
seed: 12345
data:
  _target_: cyto_dl.datamodules.folder.make_folder_dataloader
  path: 
  transforms:
    - _target_: monai.transforms.LoadImaged
      keys: input
      reader:
        - _target_: cyto_dl.image.io.MonaiBioReader
          dimension_order_out: "CZYX"
          dask_load: False
          C: 1
    - _target_: monai.transforms.NormalizeIntensityd
      keys: input
      channel_wise: true
    - _target_: monai.transforms.ToTensord
      keys: input
      dtype: float16
  num_workers: 1
  batch_size: 1
  pin_memory: True
  persistent_workers: False
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  compile: false
  save_images_every_n_epochs: 1
  x_key: ${source_col}
  save_dir: ${paths.output_dir}
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: ${model._aux.out_channels}
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    filters:
    - 16
    - 32
    - 64
    - 128
    dropout: 0.0
    res_block: true
  task_heads:
    fov_seg:
      save_input: true
      _target_: cyto_dl.nn.ResBlocksHead
      in_channels: ${model._aux.out_channels}
      out_channels: 6
      resolution: lr
      n_convs: 1
      loss:
        _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegLoss
        dim: 3
        weights:
          skeleton: 0.2
          semantic: 0.1
          boundary: 0.2
          vector: 0.2
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: -1
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: -1
          dtype: numpy.float32
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.99
  inference_args:
    roi_size: [32, 256, 256]
    sw_batch_size: 1
    overlap: 0.25
    mode: gaussian
    progress: true
  _aux:
    out_channels: 16
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 100
  accelerator: cpu
  check_val_every_n_epoch: 1
  deterministic: false
  detect_anomaly: false
  precision: 16
paths:
  root_dir: .
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir:
extras:
  ignore_warnings: true
  enforce_tags: true
  print_config: true
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: input
target_col: caaxseg
persist_cache: true
