experiment_name: workshop
run_name: instance_seg
task_name: train
tags:
- dev
train: true
test: false
ckpt_path: "//allen/aics/assay-dev/users/Benji/CurrentProjects/im2im_dev/cyto-dl/logs/train/runs/workshop/instance_seg/2024-07-17_14-34-16/checkpoints/epoch_089.ckpt"
seed: 12345
data:
  _aux:
    patch_shape: [40, 256, 256]
  _target_: cyto_dl.datamodules.array.make_array_dataloader
  data: 
  num_workers: 1
  batch_size: 1
  source_key: ${source_col}
  transforms:
    - _target_: monai.transforms.ToTensord
      keys:
      - raw
      dtype: float32
    - _target_: cyto_dl.image.transforms.clip.Clipd
      keys: raw
    - _target_: monai.transforms.NormalizeIntensityd
      keys: raw
model:
  _target_: cyto_dl.models.im2im.MultiTaskIm2Im
  compile: false
  save_images_every_n_epochs: 1
  x_key: ${source_col}
  save_dir: ${paths.output_dir}
  backbone:
    _target_: monai.networks.nets.DynUNet
    spatial_dims: 3
    in_channels: 1
    out_channels: ${model._aux.out_channels}
    strides:
    - 1
    - 2
    - 2
    - 2
    kernel_size:
    - 3
    - 3
    - 3
    - 3
    upsample_kernel_size:
    - 2
    - 2
    - 2
    filters:
    - 16
    - 32
    - 64
    - 128
    dropout: 0.0
    res_block: true
  task_heads:
    fov_seg:
      _target_: cyto_dl.nn.ResBlocksHead
      in_channels: ${model._aux.out_channels}
      out_channels: 6
      resolution: lr
      n_convs: 1
      loss:
        _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegLoss
        dim: 3
        weights:
          skeleton: 0.2
          semantic: 0.1
          boundary: 0.2
          vector: 0.2
      postprocess:
        input:
          _target_: cyto_dl.models.im2im.utils.postprocessing.ActThreshLabel
          ch: -1
          dtype: numpy.float32
        prediction:
          _target_: cyto_dl.models.im2im.utils.instance_seg.InstanceSegCluster
          min_size: 100
  optimizer:
    generator:
      _partial_: true
      _target_: torch.optim.AdamW
      lr: 0.0001
      weight_decay: 0.001
  lr_scheduler:
    generator:
      _partial_: true
      _target_: torch.optim.lr_scheduler.ExponentialLR
      gamma: 0.99
  inference_args:
    roi_size: ${data._aux.patch_shape}
    sw_batch_size: 1
    overlap: 0.25
    mode: gaussian
    progress: true
  _aux:
    out_channels: 16
callbacks:
logger:
trainer:
  _target_: lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 100
  accelerator: gpu
  devices: [0]
  precision: 16
  check_val_every_n_epoch: 10
  deterministic: false
  detect_anomaly: false
  max_time: null
paths:
  root_dir: ${oc.env:PROJECT_ROOT, './'}
  data_dir: ${paths.root_dir}/data/
  log_dir: ${paths.root_dir}/logs/
  output_dir: 
extras:
  ignore_warnings: true
  enforce_tags: False
  print_config: False
  precision:
    _target_: torch.set_float32_matmul_precision
    precision: medium
source_col: raw
target_col: caaxseg
persist_cache: true
